version: '3.8'

services:
  # ===================
  # 数据存储服务
  # ===================
  
  # Milvus 向量数据库
  milvus:
    image: milvusdb/milvus:v2.5.6
    container_name: embedai_milvus
    restart: unless-stopped
    ports:
      - "10103:19530"  # gRPC端口
      - "10191:9091"    # HTTP端口
    volumes:
      - milvus_data:/var/lib/milvus
      - milvus_logs:/var/lib/milvus/logs
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MILVUS_LOG_LEVEL=error
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    networks:
      - embedai_network
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 60s
      start_period: 120s
      timeout: 30s
      retries: 5

  # Milvus 依赖：etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: embedai_etcd
    restart: unless-stopped
    volumes:
      - etcd_data:/etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s

  # Neo4j 图数据库
  neo4j:
    image: neo4j:5.26.0
    container_name: embedai_neo4j
    restart: unless-stopped
    ports:
      - "10104:7474"  # HTTP端口
      - "10105:7687"  # Bolt端口
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/embedai123
      - NEO4J_PLUGINS=["apoc", "n10s"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "cypher-shell", "--username", "neo4j", "--password", "embedai123", "CALL db.ping() YIELD success RETURN success;"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MinIO 对象存储
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: embedai_minio
    restart: unless-stopped
    ports:
      - "10106:9000"  # API端口
      - "10107:9001"  # 控制台端口
    volumes:
      - minio_data:/minio_data
      - minio_config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
    command: minio server /minio_data --address 0.0.0.0:9000 --console-address 0.0.0.0:9001
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s

  # ===================
  # 应用服务
  # ===================

  # 后端 API 服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - APP_UID=${APP_UID:-1000}
        - APP_GID=${APP_GID:-1000}
    container_name: embedai_backend
    restart: unless-stopped
    ports:
      - "10100:10100"
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    environment:
      # 数据库连接配置
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=embedai123
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=embedai-files
      
      # API配置
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_BASE_URL=https://api.siliconflow.cn/v1
      
      # 应用配置
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:10101,http://localhost:10102
      - MAX_UPLOAD_SIZE=104857600  # 100MB
      - RATE_LIMIT_PER_MINUTE=100
    networks:
      - embedai_network
    depends_on:
      milvus:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端管理后台
  frontend_admin:
    build:
      context: ./frontend_admin
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: embedai_admin
    restart: unless-stopped
    ports:
      - "10101:10101"
    networks:
      - embedai_network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10101/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端 SDK 演示页面
  frontend_sdk:
    build:
      context: ./frontend_sdk
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: embedai_sdk
    restart: unless-stopped
    ports:
      - "10102:10102"
    networks:
      - embedai_network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10102/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# ===================
# 网络配置
# ===================
networks:
  embedai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ===================
# 数据卷配置
# ===================
volumes:
  # Milvus数据
  milvus_data:
    driver: local
  milvus_logs:
    driver: local
  
  # etcd数据
  etcd_data:
    driver: local
  
  # Neo4j数据
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  
  # MinIO数据
  minio_data:
    driver: local
  minio_config:
    driver: local
  
  # 后端数据
  backend_data:
    driver: local
  backend_logs:
    driver: local
  backend_uploads:
    driver: local
