version: '3.8'

services:
  # ===================
  # 数据存储服务
  # ===================
  
  # Milvus 向量数据库
  milvus:
    image: milvusdb/milvus:v2.5.6
    container_name: embedai_milvus
    restart: unless-stopped
    ports:
      - "10103:19530"  # gRPC端口
      - "10191:9091"    # HTTP端口
    volumes:
      - milvus_data:/var/lib/milvus
      - milvus_logs:/var/lib/milvus/logs
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MILVUS_LOG_LEVEL=error
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    networks:
      - embedai_network
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 60s
      start_period: 120s
      timeout: 30s
      retries: 5

  # Milvus 依赖：etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: embedai_etcd
    restart: unless-stopped
    volumes:
      - etcd_data:/etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s

  # Neo4j 图数据库
  neo4j:
    image: neo4j:5.26.0
    container_name: embedai_neo4j
    restart: unless-stopped
    ports:
      - "10104:7474"  # HTTP端口
      - "10105:7687"  # Bolt端口
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/embedai123
      - NEO4J_PLUGINS=["apoc", "n10s"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "cypher-shell", "--username", "neo4j", "--password", "embedai123", "CALL db.ping() YIELD success RETURN success;"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MinIO 对象存储
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: embedai_minio
    restart: unless-stopped
    ports:
      - "10106:9000"  # API端口
      - "10107:9001"  # 控制台端口
    volumes:
      - minio_data:/minio_data
      - minio_config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
    command: minio server /minio_data --address 0.0.0.0:9000 --console-address 0.0.0.0:9001
    networks:
      - embedai_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s

# ===================
# 网络配置
# ===================
networks:
  embedai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ===================
# 数据卷配置
# ===================
volumes:
  # Milvus数据
  milvus_data:
    driver: local
  milvus_logs:
    driver: local
  
  # etcd数据
  etcd_data:
    driver: local
  
  # Neo4j数据
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  
  # MinIO数据
  minio_data:
    driver: local
  minio_config:
    driver: local
